Repository ryos-io/Rhino, pull requests merged in 2019-06, with the labels that each got.

#34 Spec name fix in Grafana for Reactive pipeline.
  rhino-core/src/main/java/io/ryos/rhino/sdk/runners/ReactiveHttpSimulationRunner.java
  rhino-core/src/main/java/io/ryos/rhino/sdk/specs/HttpSpecImpl.java
  rhino-core/src/main/java/io/ryos/rhino/sdk/specs/Spec.java
Labels: bug

#33 Rename class names.
  README.md
  rhino-core/src/main/java/io/ryos/rhino/sdk/Application.java
  rhino-core/src/main/java/io/ryos/rhino/sdk/Simulation.java
  rhino-core/src/main/java/io/ryos/rhino/sdk/SimulationConfig.java
  rhino-core/src/main/java/io/ryos/rhino/sdk/SimulationImpl.java
  rhino-core/src/main/java/io/ryos/rhino/sdk/SimulationJobsScanner.java
  rhino-core/src/main/java/io/ryos/rhino/sdk/SimulationJobsScannerImpl.java
  rhino-core/src/main/java/io/ryos/rhino/sdk/SimulationMetadata.java
  rhino-core/src/main/java/io/ryos/rhino/sdk/SimulationSpec.java
  rhino-core/src/main/java/io/ryos/rhino/sdk/runners/DefaultSimulationRunner.java
  rhino-core/src/main/java/io/ryos/rhino/sdk/runners/ReactiveHttpSimulationRunner.java
  rhino-core/src/main/java/io/ryos/rhino/sdk/runners/SimulationRunner.java
  rhino-core/src/main/java/io/ryos/rhino/sdk/specs/HttpSpecAsyncHandler.java
  rhino-core/src/test/java/io/ryos/rhino/sdk/PerformanceScenarioSpecImplTest.java
  rhino-core/src/test/java/io/ryos/rhino/sdk/PerformanceTestingExampleWithoutUser.java
  rhino-wiki/GettingStarted.md
Labels: enhancement

#32 Classpath/absolute file based resources support
  rhino-core/src/main/java/io/ryos/rhino/sdk/SimulationConfig.java
  rhino-core/src/main/java/io/ryos/rhino/sdk/io/ConfigResource.java
  rhino-core/src/main/java/io/ryos/rhino/sdk/users/CSVUserParserImpl.java
  rhino-core/src/main/java/io/ryos/rhino/sdk/users/provider/FileBasedUserProviderImpl.java
  rhino-core/src/main/java/io/ryos/rhino/sdk/users/provider/UserProvider.java
  rhino-core/src/test/java/io/ryos/rhino/sdk/io/ConfigResourceTest.java
Labels: enhancement

#41 SimulationMetadata class break into cohesive components
  rhino-core/src/main/java/io/ryos/rhino/sdk/SimulationJobsScannerImpl.java
  rhino-core/src/main/java/io/ryos/rhino/sdk/SimulationMetadata.java
  rhino-core/src/main/java/io/ryos/rhino/sdk/runners/DefaultSimulationCallable.java
  rhino-core/src/main/java/io/ryos/rhino/sdk/runners/DefaultSimulationRunner.java
  rhino-core/src/main/java/io/ryos/rhino/sdk/runners/EventDispatcher.java
  rhino-core/src/main/java/io/ryos/rhino/sdk/runners/ReactiveHttpSimulationRunner.java
  rhino-core/src/main/java/io/ryos/rhino/sdk/specs/HttpSpecAsyncHandler.java
  rhino-core/src/test/java/io/ryos/rhino/sdk/PerformanceScenarioSpecImplTest.java
  rhino-core/src/test/java/io/ryos/rhino/sdk/PerformanceTestingExampleWithoutUser.java
  rhino-core/src/test/resources/rhino.properties
Labels: enhancement

#42 Load DSL for reactive load generators.
  README.md
  rhino-core/src/main/java/io/ryos/rhino/sdk/SimulationJobsScannerImpl.java
  rhino-core/src/main/java/io/ryos/rhino/sdk/annotations/Dsl.java
  rhino-core/src/main/java/io/ryos/rhino/sdk/data/Context.java
  rhino-core/src/main/java/io/ryos/rhino/sdk/data/ContextImpl.java
  rhino-core/src/main/java/io/ryos/rhino/sdk/dsl/CollectorDsl.java
  rhino-core/src/main/java/io/ryos/rhino/sdk/dsl/ExecContext.java
  rhino-core/src/main/java/io/ryos/rhino/sdk/dsl/Executable.java
  rhino-core/src/main/java/io/ryos/rhino/sdk/dsl/HttpExecContext.java
  rhino-core/src/main/java/io/ryos/rhino/sdk/dsl/HttpExecutable.java
  rhino-core/src/main/java/io/ryos/rhino/sdk/dsl/LoadDsl.java
  rhino-core/src/main/java/io/ryos/rhino/sdk/dsl/SpecMaterializer.java
  rhino-core/src/main/java/io/ryos/rhino/sdk/dsl/Start.java
  rhino-core/src/main/java/io/ryos/rhino/sdk/reporting/StdoutReporter.java
  rhino-core/src/main/java/io/ryos/rhino/sdk/runners/DefaultSimulationCallable.java
  rhino-core/src/main/java/io/ryos/rhino/sdk/runners/DefaultSimulationRunner.java
  rhino-core/src/main/java/io/ryos/rhino/sdk/runners/EventDispatcher.java
  rhino-core/src/main/java/io/ryos/rhino/sdk/runners/ReactiveHttpSimulationRunner.java
  rhino-core/src/main/java/io/ryos/rhino/sdk/specs/AbstractSpec.java
  rhino-core/src/main/java/io/ryos/rhino/sdk/specs/HttpSpec.java
  rhino-core/src/main/java/io/ryos/rhino/sdk/specs/HttpSpecAsyncHandler.java
  rhino-core/src/main/java/io/ryos/rhino/sdk/specs/HttpSpecImpl.java
  rhino-core/src/main/java/io/ryos/rhino/sdk/specs/Spec.java
  rhino-core/src/main/java/io/ryos/rhino/sdk/users/data/User.java
  rhino-core/src/test/java/io/ryos/rhino/sdk/ReactiveTestSimulation.java
  rhino-core/src/test/java/io/ryos/rhino/sdk/specs/DslTest.java
  rhino-core/src/test/resources/rhino.properties
Labels: enhancement

#46 The HTTP query params into the right map
  rhino-core/src/main/java/io/ryos/rhino/sdk/specs/HttpSpecImpl.java
Labels: bug

#47 Upload content supplier to avoid the same stream to be used.
  rhino-core/src/main/java/io/ryos/rhino/sdk/dsl/HttpSpecMaterializer.java
  rhino-core/src/main/java/io/ryos/rhino/sdk/specs/HttpSpec.java
  rhino-core/src/main/java/io/ryos/rhino/sdk/specs/HttpSpecImpl.java
Labels: bug

#50 Throttling and rampup
  pom.xml
  rhino-core/pom.xml
  rhino-core/src/main/java/io/ryos/rhino/sdk/RampupInfo.java
  rhino-core/src/main/java/io/ryos/rhino/sdk/SimulationJobsScannerImpl.java
  rhino-core/src/main/java/io/ryos/rhino/sdk/SimulationMetadata.java
  rhino-core/src/main/java/io/ryos/rhino/sdk/ThrottlingInfo.java
  rhino-core/src/main/java/io/ryos/rhino/sdk/annotations/RampUp.java
  rhino-core/src/main/java/io/ryos/rhino/sdk/annotations/Throttle.java
  rhino-core/src/main/java/io/ryos/rhino/sdk/runners/Rampup.java
  rhino-core/src/main/java/io/ryos/rhino/sdk/runners/ReactiveHttpSimulationRunner.java
  rhino-core/src/main/java/io/ryos/rhino/sdk/runners/Throttler.java
  rhino-core/src/main/resources/log4j2.xml
  rhino-core/src/test/java/io/ryos/rhino/sdk/BlockingLoadTestWithoutUserSimulation.java
  rhino-core/src/test/java/io/ryos/rhino/sdk/FluxTests.java
  rhino-core/src/test/java/io/ryos/rhino/sdk/ReactiveBasicHttpGetSimulation.java
  rhino-core/src/test/java/io/ryos/rhino/sdk/ReactiveSleepTestSimulation.java
  rhino-core/src/test/resources/log4j2.xml
  rhino-hello-world/pom.xml
Labels: do not merge

#49 Retry Spec
  rhino-core/src/main/java/io/ryos/rhino/sdk/dsl/HttpSpecMaterializer.java
  rhino-core/src/main/java/io/ryos/rhino/sdk/exceptions/RetryableOperationException.java
  rhino-core/src/main/java/io/ryos/rhino/sdk/runners/ReactiveHttpSimulationRunner.java
  rhino-core/src/main/java/io/ryos/rhino/sdk/specs/HttpResponse.java
  rhino-core/src/main/java/io/ryos/rhino/sdk/specs/HttpSpec.java
  rhino-core/src/main/java/io/ryos/rhino/sdk/specs/HttpSpecImpl.java
  rhino-core/src/main/java/io/ryos/rhino/sdk/specs/RetriableSpec.java
  rhino-core/src/test/java/io/ryos/rhino/sdk/ReactiveBasicHttpGetSimulation.java
  rhino-core/src/test/java/io/ryos/rhino/sdk/RetrySpecTest.java
Labels: enhancement
